baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'éƒ­æµ·æ—çš„åšå®¢'
theme = 'github-style'
lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
  author = "éƒ­æµ·æ—"
  description = "In solitude, where we are least alone."
  github = "ghlyibu"
  email = "ghlluck@foxmail.com"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true
  enableSearch = true
[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false
